// Generated by CoffeeScript 1.12.3
(function() {
  'use strict';
  var get, isInside, make, proto, set;

  isInside = function(arg) {
    var x, y;
    x = arg.x, y = arg.y;
    return (0 <= x && x < this.size.x) && (0 <= y && y < this.size.y);
  };

  get = function(arg) {
    var x, y;
    x = arg.x, y = arg.y;
    return this.lines[y][x];
  };

  set = function(arg, value) {
    var x, y;
    x = arg.x, y = arg.y;
    this.lines[y][x] = value;
  };

  proto = {
    get: get,
    set: set,
    isInside: isInside
  };

  make = function(size) {
    var i, instance, j, k, l, line, lines, ref, ref1;
    lines = [];
    for (i = k = 0, ref = size.y; 0 <= ref ? k < ref : k > ref; i = 0 <= ref ? ++k : --k) {
      line = [];
      for (j = l = 0, ref1 = size.x; 0 <= ref1 ? l < ref1 : l > ref1; j = 0 <= ref1 ? ++l : --l) {
        line.push(null);
      }
      lines.push(line);
    }
    instance = Object.create(proto);
    Object.assign(instance, {
      size: size,
      lines: lines
    });
    Object.freeze(instance);
    return instance;
  };

  if (window.Board == null) {
    window.Board = {};
  }

  Object.assign(window.Board, {
    make: make
  });

}).call(this);
