// Generated by CoffeeScript 1.12.3
(function() {
  'use strict';
  var getFlipHorizontal, getFlipVertical, getFlips, getNeighbors, getOptions, getRotations, getSignature, getTiles, getTileset, getVariants, groupBy, indexBy, tileDataToImage,
    slice = [].slice;

  indexBy = Util.indexBy, groupBy = Util.groupBy;

  getSignature = function(arg) {
    var down, left, right, tileData, up, zero;
    tileData = arg.tileData;
    zero = Vec2.make(0, 0);
    up = tileData.getStripe(zero, Vec2.make(1, 0), tileData.size.x);
    down = tileData.getStripe(zero.down(tileData.size.y - 1), Vec2.make(1, 0), tileData.size.x);
    left = tileData.getStripe(zero, Vec2.make(0, 1), tileData.size.y);
    right = tileData.getStripe(zero.right(tileData.size.x - 1), Vec2.make(0, 1), tileData.size.y);
    return {
      up: up.toString(),
      down: down.toString(),
      left: left.toString(),
      right: right.toString()
    };
  };

  getOptions = function(tile) {
    var get, zero;
    get = tile.get.bind(tile);
    zero = Vec2.make(0, 0);
    return {
      weight: (get(zero))[0] / 255,
      rotations: (get(zero.right(1)))[0] > 127,
      flip: {
        vertical: (get(zero.right(2)))[0] > 127,
        horizontal: (get(zero.right(3)))[0] > 127
      }
    };
  };

  getNeighbors = function(tilesBySignature, tile) {
    var down, left, right, up;
    up = tilesBySignature.down.has(tile.signature.up) ? tilesBySignature.down.get(tile.signature.up) : [];
    down = tilesBySignature.up.has(tile.signature.down) ? tilesBySignature.up.get(tile.signature.down) : [];
    left = tilesBySignature.right.has(tile.signature.left) ? tilesBySignature.right.get(tile.signature.left) : [];
    right = tilesBySignature.left.has(tile.signature.right) ? tilesBySignature.left.get(tile.signature.right) : [];
    return {
      up: up,
      down: down,
      left: left,
      right: right
    };
  };

  getRotations = function(tileData, id, arg) {
    var rotated180, rotations;
    rotations = arg.rotations;
    if (rotations) {
      rotated180 = tileData.rotate180();
      if (rotated180.equals(tileData)) {
        return [
          {
            id: id + "-90",
            tileData: tileData.rotate90()
          }
        ];
      } else {
        return [
          {
            id: id + "-90",
            tileData: tileData.rotate90()
          }, {
            id: id + "-180",
            tileData: rotated180
          }, {
            id: id + "-270",
            tileData: tileData.rotate270()
          }
        ];
      }
    } else {
      return [];
    }
  };

  getFlipHorizontal = function(tileData, id, arg) {
    var flip, flippedHorizontal;
    flip = arg.flip;
    if (flip.horizontal) {
      flippedHorizontal = tileData.flipHorizontal();
      if (flippedHorizontal.equals(tileData)) {
        return [];
      } else {
        return [
          {
            id: id + "-h",
            tileData: flippedHorizontal
          }
        ];
      }
    } else {
      return [];
    }
  };

  getFlipVertical = function(tileData, id, arg) {
    var flip, flippedVertical;
    flip = arg.flip;
    if (flip.vertical) {
      flippedVertical = tileData.flipVertical();
      if (flippedVertical.equals(tileData)) {
        return [];
      } else {
        return [
          {
            id: id + "-v",
            tileData: flippedVertical
          }
        ];
      }
    } else {
      return [];
    }
  };

  getFlips = function(tileData, id, arg) {
    var flip, flips;
    flip = arg.flip;
    flips = slice.call(getFlipHorizontal(tileData, id, {
        flip: flip
      })).concat(slice.call(getFlipVertical(tileData, id, {
        flip: flip
      })));
    if (flips.length === 2 && flips[0].tileData.equals(flips[1].tileData)) {
      return [flips[0]];
    } else {
      return flips;
    }
  };

  getVariants = function(tileData, id, arg) {
    var flip, rotations;
    rotations = arg.rotations, flip = arg.flip;
    return [{
        id: id,
        tileData: tileData
      }].concat(slice.call(getRotations(tileData, id, {
        rotations: rotations
      })), slice.call(getFlips(tileData, id, {
        flip: flip
      })));
  };

  getTiles = (function() {
    var offset, padding;
    padding = {
      x: 2,
      y: 4
    };
    offset = {
      x: 1,
      y: 1
    };
    return function(canvas, size) {
      var cellSize, context, i, id, j, k, l, options, optionsData, original, ref, ref1, tileData, tiles, variants;
      context = canvas.getContext('2d');
      cellSize = Vec2.make(Math.floor(canvas.width / size.x) - padding.x, Math.floor(canvas.height / size.y) - padding.y);
      tiles = [];
      for (i = k = 0, ref = size.x; 0 <= ref ? k < ref : k > ref; i = 0 <= ref ? ++k : --k) {
        for (j = l = 0, ref1 = size.y; 0 <= ref1 ? l < ref1 : l > ref1; j = 0 <= ref1 ? ++l : --l) {
          tileData = context.getImageData(i * (cellSize.x + padding.x) + offset.x, j * (cellSize.y + padding.y) + offset.y, cellSize.x, cellSize.y).data;
          original = TileData.make(tileData, cellSize);
          optionsData = context.getImageData(i * (cellSize.x + padding.x) + offset.x, j * (cellSize.y + padding.y) + cellSize.y + offset.y * 2, cellSize.x, 1).data;
          id = "t" + i + "-" + j;
          options = getOptions(TileData.make(optionsData, {
            x: cellSize.x,
            y: 1
          }));
          variants = getVariants(original, id, options);
          variants.forEach(function(variant) {
            var signature;
            signature = getSignature(variant);
            Object.assign(variant, options, {
              signature: signature
            });
          });
          tiles.push.apply(tiles, variants);
        }
      }
      return tiles;
    };
  })();

  tileDataToImage = function(arg) {
    var canvas, context, data, imageData, size;
    data = arg.data, size = arg.size;
    canvas = document.createElement('canvas');
    canvas.width = size.x;
    canvas.height = size.y;
    context = canvas.getContext('2d');
    imageData = new ImageData(new Uint8ClampedArray(data), size.x, size.y);
    context.putImageData(imageData, 0, 0);
    return new Promise(function(resolve, reject) {
      var image;
      image = new Image;
      image.src = canvas.toDataURL();
      return image.addEventListener('load', function() {
        resolve(image);
      });
    });
  };

  getTileset = function(canvas, size) {
    var tiles, tilesBySignature;
    tiles = getTiles(canvas, size);
    tilesBySignature = {
      up: groupBy(tiles, function(tile) {
        return tile.signature.up;
      }),
      down: groupBy(tiles, function(tile) {
        return tile.signature.down;
      }),
      left: groupBy(tiles, function(tile) {
        return tile.signature.left;
      }),
      right: groupBy(tiles, function(tile) {
        return tile.signature.right;
      })
    };
    tiles.forEach(function(tile) {
      tile.neighbors = getNeighbors(tilesBySignature, tile);
    });
    return Promise.all(tiles.map(function(tile) {
      return (tileDataToImage(tile.tileData)).then(function(image) {
        return tile.image = image;
      });
    })).then(function() {
      return indexBy(tiles, function(arg) {
        var id;
        id = arg.id;
        return id;
      });
    });
  };

  if (window.Tileset == null) {
    window.Tileset = {};
  }

  Object.assign(window.Tileset, {
    getTileset: getTileset
  });

}).call(this);
