// Generated by CoffeeScript 1.12.3
(function() {
  'use strict';
  var add, down, equals, left, make, proto, right, up;

  up = function(amount) {
    if (amount == null) {
      amount = 1;
    }
    return make(this.x, this.y - amount);
  };

  down = function(amount) {
    if (amount == null) {
      amount = 1;
    }
    return make(this.x, this.y + amount);
  };

  left = function(amount) {
    if (amount == null) {
      amount = 1;
    }
    return make(this.x - amount, this.y);
  };

  right = function(amount) {
    if (amount == null) {
      amount = 1;
    }
    return make(this.x + amount, this.y);
  };

  add = function(arg) {
    var x, y;
    x = arg.x, y = arg.y;
    return make(this.x + x, this.y + y);
  };

  equals = function(arg) {
    var x, y;
    x = arg.x, y = arg.y;
    return this.x === x && this.y === y;
  };

  proto = {
    up: up,
    down: down,
    left: left,
    right: right,
    add: add,
    equals: equals
  };

  make = function(x, y) {
    var instance;
    instance = Object.create(proto);
    Object.assign(instance, {
      x: x,
      y: y
    });
    Object.freeze(instance);
    return instance;
  };

  if (window.Vec2 == null) {
    window.Vec2 = {};
  }

  Object.assign(window.Vec2, {
    make: make
  });

}).call(this);
